### ISSUE TITLE
SALTs should not be allowed to be empty when starting SATOSA

### ISSUE THREAD

**Issue by surfnet-niels** [its-dirg/SATOSA#11]
SATOSA supports SALTing in various places, which is good. However if SALTs end up empty (neither being set via proxy config or env variable) this does not yield a WARN (or maybe even a full stop).
Not SALTing is probably not a good idea from a security point of view

**Comment by rebeckag** [comment]
I can't reproduce this on master with either `STATE_ENCRYPTION_KEY` or `USER_ID_HASH_SALT`. Is any other config param affected?
