### ISSUE TITLE
Fails if URL is hard-coded other than the actual destination 

### ISSUE THREAD

**Issue by RD1991** [its-dirg/SATOSA#54]
In src/frontends/saml2.py 

In the method : 
    def _handle_authn_response(self, context, internal_response, idp):
Im customising the destination from 
http_args = idp.apply_binding(resp_args["binding"], str(resp), resp_args["destination"],
                                      request_state["relay_state"], response=True)
        to 
http_args = idp.apply_binding(resp_args["binding"], str(resp), 'https://public-ip-address:5050/',
                                      request_state["relay_state"], response=True)
but this fails. 

Any suggestions ?

**Comment by rebeckag** [comment]
Is there any error message?
What are you trying to achieve, why use a hardcoded URL?

**Comment by RD1991** [comment]
I need to redirect from SATOSA to another node proxy , so I'm hardcoding URL (testing purpose).

Client -> SATOSA -> IDP -> SATOSA -> PROXY (this proxy does not include all the headers) -> Client 

If I didn't hardcode the URL , it works fine.

**Comment by rebeckag** [comment]
I've started to look into this, but I can't reproduce your error.
If I hardcode an URL as in the example in OP, the SAMLResponse is sent to that URL without any error.

Do you get any error message?

**Comment by RD1991** [comment]
I don't get any error messages, but also not able to receive all the header parameters to the new proxy.

**Comment by rebeckag** [comment]
What headers are you missing?

**Comment by RD1991** [comment]
set-cookie headers are missing

**Comment by rebeckag** [comment]
I can't reproduce that either.
SATOSA properly deletes it's own cookie (as named in `proxy_conf.yaml`) in response to the authentication response arriving at the endpoint.
What Set-Cookie header are you expecting?

**Comment by RD1991** [comment]
Im achieving SSO with dropbox. 
So dropbox gives login saml response to satosa and then satosa 'POST' it to proxy. But the 'set-cookies' from dropbox to satosa and dropped when they are newly sent to proxy. 

SetCookie() method which newly creates cookie , deletes the old one ?

**Comment by rebeckag** [comment]
The cookie from Dropbox shouldn't be forwarded by SATOSA.
The browser will handle the Set-Cookie header, so the cookie not being sent to your proxy is expected.
This should be possible to verify by inspecting the cookies set in your browser after a full round trip.

**Comment by RD1991** [comment]
Ok, so after knowing my problem do you have any solution over this ?

**Comment by rebeckag** [comment]
Not really, since there is no ways for SATOSA to forward the cookie from Dropbox to your server.
As I mentioned earlier, it's the proper behaviour that the cookie only reaches the browser and is not sent to your proxy.

**Comment by RD1991** [comment]
Ok, thanks and sorry for buzzing
