### ISSUE TITLE
Is the remote metadata example correct?

### ISSUE THREAD

**Issue by surfnet-niels** [its-dirg/SATOSA#9]
The metadata example for remote URL shows:

"metadata": {
    "remote": 
        -url:https://kalmar2.org/simplesaml/module.php/aggregator/?id=kalmarcentral2&set=saml2,
        -cert:null
}

However, pySAML (https://dirg.org.umu.se/static/pysaml2/howto/config.html#metadata) shows:
"metadata" : {
    "local": [
        "metadata.xml", "vo_metadata.xml"
        ],
    "remote": [
        {
            "url":"https://kalmar2.org/simplesaml/module.php/aggregator/?id=kalmarcentral2&set=saml2",
            "cert":"kalmar2.cert"
        }],
},

Which could also be like so:
    metadata:  
      remote:
        - url:https://kalmar2.org/simplesaml/module.php/aggregator/?id=kalmarcentral2&set=saml2,
          cert:null
    
But not as presented in the example?

**Comment by rebeckag** [comment]
Fixed, thanks! :)
